Nao?

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -112,13 +112,12 @@ jobs:
           tag: "rel-${{ steps.date.outputs.date }}"
           token: ${{ secrets.GITHUB_TOKEN }}
 
-  resourcerevisiontags:
-    # We additionally create tags to track the source commit of specific
-    # resource revisions in CharmHub
-    name: Create Git resource-revision tags
+  charmhubrelease:
+    name: Release to CharmHub
     runs-on: ubuntu-latest
     needs:
-      - build
+      - ghrelease
+      - resourcerevisiontags
     strategy:
       matrix:
         arch: [amd64, arm64]
@@ -126,43 +125,33 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v2
+      - name: Download artifacts
+        uses: actions/download-artifact@v3
+        with:
+          path: artifacts/
       - name: Install charmcraft
         run: |
           sudo snap install charmcraft --classic
-      - name: Retrieve current revision number
-        id: getrev
+      - id: charmhubupload
+        name: Upload ${{matrix.arch}} resource revision to ${{matrix.arch}} charm
         env:
           CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
-        # Get the latest amd64 revision in CharmHub and increments it by one.
-        # This assumes that the amd64 and arm64 revisions are in lockstep.
         run: |
-          echo "::set-output name=rev::$(($(charmcraft resource-revisions ${{ matrix.charm }} promql-transform-${{matrix.arch}} | tail -n+2 | head -1 | awk '{ print $1 }') + 1))"
-      - name: Create tag for ${{matrix.charm}} charm, ${{matrix.arch}} architecture
+          if output=$(charmcraft upload-resource ${{ matrix.charm }} promql-transform-${{matrix.arch}} --file artifacts/promql-transform-${{matrix.arch}}); then
+            if revision=$(echo "${output}" | sed 's/^Revision \([0-9]\{1,\}\) .*$/\1/'); then
+              echo "::set-output name=rev::${revision}"
+            fi
+          else
+            echo "charmcraft upload-resource failed: ${output}"
+            exit 1
+          fi
+
+          if [ -z "${revision}" ]; then
+            echo "No revision found in the output of charmcraft upload-resource:\n${output}"
+            exit 2
+          fi
+      - name: Create git tag for ${{matrix.charm}} charm, ${{matrix.arch}} architecture
         uses: rickstaa/action-create-tag@v1
         with:
-          tag: "${{ matrix.charm }}-rev${{ steps.getrev.outputs.rev }}"
-          message: "Resource revision ${{ matrix.charm }}/${{ steps.getrev.outputs.rev }}"
-
-  # charmhub:
-  #   name: Release to CharmHub
-  #   runs-on: ubuntu-latest
-  #   needs:
-  #     - ghrelease
-  #     - resourcerevisiontags
-  #   strategy:
-  #     matrix:
-  #       arch: [amd64, arm64]
-  #       charm: [prometheus-k8s, grafana-k8s]
-  #   steps:
-  #     - name: Download artifacts
-  #       uses: actions/download-artifact@v3
-  #       with:
-  #         path: artifacts/
-  #     - name: Install charmcraft
-  #       run: |
-  #         sudo snap install charmcraft --classic
-  #     - name: Upload ${{matrix.arch}} resource revision to ${{matrix.arch}} charm
-  #       env:
-  #         CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
-  #       run: |
-  #         charmcraft upload-resource ${{ matrix.charm }} promql-transform-${{matrix.arch}} --file artifacts/promql-transform-${{matrix.arch}}
+          tag: "${{ matrix.charm }}-rev${{ steps.charmhubupload.outputs.rev }}"
+          message: "Resource revision ${{ matrix.charm }}/${{ steps.charmhubupload.outputs.rev }}"
